import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import AuthProvider from "./auth/Provider";
import AuthGuard from "./AuthGuard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  referrer: "no-referrer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-hidden bg-gradient-to-br from-[#e0f7ff] to-[#ffffff]`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <AuthGuard>
              <Theme appearance="light">
                <NavBar />
                <main className="min-h-screen bg-gradient-to-br from-[#e0f7ff] to-[#ffffff]">
                  {children}
                </main>
              </Theme>
            </AuthGuard>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
